"""Generate distribution notices from installed/restored dependencies, offline.

Run npm ci in LuminaVault-Frontend and dotnet restore for the backend first.
Use --check to detect stale notices without writing files.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "LuminaVault-Frontend"
BACKEND = ROOT / "LuminaVault-Backend"
UPSTREAM = ROOT / "licenses" / "upstream"
NOTICE_NAME = re.compile(r"^(licen[cs]e|copying|notice|copyright|thirdparty)", re.I)
LICENSE_NAME = re.compile(r"^(licen[cs]e|copying)", re.I)
SEPARATOR = "\n" + "=" * 78 + "\n"


def read(path):
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")


def text_file(text):
    return (text.rstrip() + "\n").encode("utf-8")


def person(value):
    if isinstance(value, dict):
        return value.get("name", "")
    if isinstance(value, list):
        return ", ".join(person(item) for item in value)
    return value or ""


def repository(value):
    return value.get("url", "") if isinstance(value, dict) else value or ""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {}
    manifest = json.loads(read(UPSTREAM / "sources.json"))
    sources = {item["file"]: item for item in manifest["sources"]}
    for filename, info in sources.items():
        if hashlib.sha256((UPSTREAM / filename).read_bytes()).hexdigest() != info["sha256"]:
            raise ValueError(f"Upstream source changed: {filename}; review its provenance")

    project_license = read(ROOT / "LICENSE")
    mit_terms = project_license[project_license.index("Permission is hereby granted"):]
    apache_terms = read(UPSTREAM / "tessdata-LICENSE.txt")
    outputs[FRONTEND / "public/LICENSE.txt"] = text_file(project_license)
    outputs[BACKEND / "LICENSE"] = text_file(project_license)

    def source_section(filename):
        info = sources[filename]
        return (f"{info['description']}\nSource: {info['url']}\n"
                f"SHA-256 of upstream text: {info['sha256']}\n\n"
                + read(UPSTREAM / filename))

    intro = ("LuminaVault third-party notices\n\n"
             "LuminaVault's original code is MIT-licensed; these third-party components\n"
             "retain their own copyrights and licenses. Inclusion below is attribution,\n"
             "not a claim that every component is used in every deployment.\n"
             "Generated by scripts/update-license-notices.py; do not edit this file.\n")
    frontend_sections = [intro, "Frontend production dependency graph (including copied OCR runtime assets).\n"
                         "Development-only tools are not distributed in the application.\n"]
    lock = json.loads(read(FRONTEND / "package-lock.json"))
    frontend_count = 0
    for relative, entry in sorted(lock["packages"].items()):
        if not relative or entry.get("dev"):
            continue
        folder = FRONTEND / relative
        package = json.loads(read(folder / "package.json"))
        if package["version"] != entry["version"]:
            raise ValueError(f"Run npm ci: installed version differs for {relative}")
        frontend_count += 1
        name, version = package["name"], package["version"]
        section = (f"{name}@{version}\nPackage: https://www.npmjs.com/package/{name}/v/{version}\n"
                   f"Declared license: {entry.get('license', 'UNSPECIFIED')}\n"
                   f"Author: {person(package.get('author'))}\n"
                   f"Source: {repository(package.get('repository'))}\n")
        files = sorted((p for p in folder.iterdir() if p.is_file() and NOTICE_NAME.match(p.name)),
                       key=lambda p: p.name)
        if name == "gsap" and version == "3.15.0":
            section += "\nCopyright (c) 2008-2026, GreenSock. All rights reserved.\n"
            section += source_section("gsap-standard-license.txt")
        elif name == "tr46" and version == "0.0.3" and not files:
            # This release declares MIT and its author but omits a license file.
            section += "\nMIT terms for the license declared in this package's metadata:\n\n" + mit_terms
        elif not any(LICENSE_NAME.match(p.name) for p in files):
            raise ValueError(f"No license text found for {name}@{version}; review before releasing")
        if name == "primeng":
            section += "\nThis is the community version. The MIT section below applies; the LTS section\nonly applies to versions with an -lts suffix.\n"
        for file in files:
            section += f"\n--- {file.name} ---\n" + read(file)
        frontend_sections.append(section)

    if lock["packages"]["node_modules/tesseract.js-core"]["version"] != "7.0.0":
        raise ValueError("Review and update native OCR source revisions for the new core version")
    frontend_sections.append("OCR native/runtime supplemental notices\n\n"
        "These texts cover native dependencies and runtime libraries referenced by\n"
        "Tesseract.js core 7.0.0's source/build configuration, including components\n"
        "that may be omitted from particular WASM variants. Source revision:\n"
        f"https://github.com/naptha/tesseract.js-core/tree/{manifest['tesseractCoreRevision']}\n\n"
        "This software is based in part on the work of the Independent JPEG Group.\n"
        "OpenLibm's notice also describes LGPL test files; those tests are not\n"
        "part of the redistributed OCR runtime.\n")
    for item in manifest["sources"]:
        if item["group"] in ("ocr", "model"):
            frontend_sections.append(source_section(item["file"]))
    outputs[FRONTEND / "public/THIRD_PARTY_NOTICES.txt"] = text_file(SEPARATOR.join(frontend_sections))

    model_dir = FRONTEND / "public/tesseract/lang"
    model = model_dir / "eng.traineddata.gz"
    digest = hashlib.sha256(model.read_bytes()).hexdigest()
    if digest != manifest["languageModelSha256"]:
        raise ValueError("The OCR language model changed; verify its origin and update provenance")
    outputs[model_dir / "LICENSE.txt"] = text_file(apache_terms)
    outputs[model_dir / "NOTICE.txt"] = text_file(
        "English OCR language model for Tesseract.js\n\n"
        "File: eng.traineddata.gz (4.0.0_best_int)\n"
        "Upstream: naptha/tessdata, Tesseract OCR project and contributors\n"
        f"Source: https://github.com/naptha/tessdata/blob/{manifest['languageModelRevision']}/4.0.0_best_int/eng.traineddata.gz\n"
        f"SHA-256: {digest}\n"
        "License: Apache-2.0; see LICENSE.txt in this directory.\n"
        "The compressed file is redistributed unchanged.\n"
        "Additional worker, WASM and native-library notices: /THIRD_PARTY_NOTICES.txt\n")

    backend_sections = [intro, "Backend restored dependency graph, including design-time dependencies.\n"
                        "The .NET runtime and container OS retain the notices supplied by their distributors.\n"]
    assets = json.loads(read(BACKEND / "obj/project.assets.json"))
    backend_count = 0
    for identity, entry in sorted(assets["libraries"].items()):
        if entry["type"] != "package":
            continue
        if identity.startswith("Microsoft.VisualStudio.Azure.Containers.Tools.Targets/"):
            raise ValueError("Proprietary container tooling must not be restored into the release graph")
        backend_count += 1
        folder = next((Path(p) / entry["path"] for p in assets["packageFolders"]
                       if (Path(p) / entry["path"]).exists()), None)
        if folder is None:
            raise ValueError(f"Restore packages first: missing {identity}")
        xml = ET.parse(next(folder.glob("*.nuspec"))).getroot()
        metadata = next(e for e in xml if e.tag.split("}")[-1] == "metadata")
        fields = {e.tag.split("}")[-1]: e for e in metadata}
        values = {name: e.text or "" for name, e in fields.items()}
        license_id = values.get("license", values.get("licenseUrl", ""))
        section = (f"{identity}\nPackage: https://www.nuget.org/packages/{identity}\n"
                   f"Declared license: {license_id}\nAuthor(s): {values.get('authors', '')}\n"
                   f"{values.get('copyright', '')}\n")
        if "repository" in fields:
            section += f"Source: {fields['repository'].get('url', '')}\n"
        files = sorted((p for p in folder.rglob("*") if p.is_file() and NOTICE_NAME.match(p.name)),
                       key=lambda p: p.relative_to(folder).as_posix())
        has_license = any(LICENSE_NAME.match(p.name) for p in files)
        if identity == "BCrypt.Net-Next/4.0.3":
            section += "\n" + source_section("bcrypt-4.0.3.txt")
        elif not has_license:
            if license_id not in ("MIT", "Apache-2.0"):
                raise ValueError(f"Review missing license text: {identity} ({license_id})")
            section += "\n" + (mit_terms if license_id == "MIT" else apache_terms)
        for file in files:
            label = file.relative_to(folder).as_posix()
            if file.suffix.lower() == ".rtf":
                # Preserve the vendor's original rich-text notice without a lossy conversion.
                destination = BACKEND / "licenses" / identity.replace("/", "-") / file.name
                outputs[destination] = file.read_bytes()
                section += f"\nAdditional original notice: {destination.relative_to(BACKEND).as_posix()}\n"
            else:
                section += f"\n--- {label} ---\n" + read(file)
        backend_sections.append(section)
    backend_sections.append("SQLite native engine\nSQLite is in the public domain.\n"
                            "https://www.sqlite.org/copyright.html\n"
                            "The SQLitePCLRaw wrappers retain their Apache-2.0 terms above.\n")
    outputs[BACKEND / "THIRD_PARTY_NOTICES.txt"] = text_file(SEPARATOR.join(backend_sections))

    stale = []
    for path, data in outputs.items():
        if args.check:
            # Git checkouts may normalize text line endings on Windows.
            existing = path.read_bytes().replace(b"\r\n", b"\n") if path.exists() else None
            if existing != data.replace(b"\r\n", b"\n"):
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    if stale:
        raise SystemExit("Stale or missing notices; run this script without --check:\n" + "\n".join(stale))
    print(f"{'Checked' if args.check else 'Generated'} notices for {frontend_count} npm entries, "
          f"{backend_count} NuGet packages and bundled OCR assets ({len(outputs)} files).")


if __name__ == "__main__":
    main()
